WITH INIT_TBL_0 AS (
SELECT *
FROM WELL_STICKS_TBL
WHERE ROW_EXPIRY_DATE > CURRENT_DATE AND ROW_DELETED_DATE IS NULL OR ROW_DELETED_DATE > CURRENT_DATE
)

, INIT_TBL AS (
SELECT 
ID, FTP_X, FTP_Y, LTP_X, LTP_Y
FROM INIT_TBL_0
GROUP BY ID
HAVING ID IS NOT NULL
)

, GEOM_1_TBL AS (
SELECT ID, 
TRY_TO_GEOMETRY(
        'LINESTRING(' || 
        FTP_X || ' ' || FTP_Y || ', ' || 
        LTP_X || ' ' || LTP_Y || ')'
    )
    AS GEOM_LINE,
ST_SETSRID(GEOM_LINE, 32040) AS GEOM_LINE_32040
FROM INIT_TBL
WHERE GEOM_LINE IS NOT NULL)

SELECT ID, ST_ASWKB(GEOM_LINE_32040) AS GEOM_LINE_32040_WKB
FROM GEOM_1_TBL